# Generated by Django 4.1.3 on 2022-11-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="Title",
            field=models.CharField(max_length=200),
        ),
    ]
