# Generated by Django 4.1.3 on 2022-11-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_text_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Date",
            field=models.DateField(),
        ),
    ]
