# Generated by Django 4.1.3 on 2022-11-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="title",
            new_name="titleman",
        ),
    ]
